# Generated by Django 4.1.3 on 2022-12-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0002_capdata_file_path2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capdata',
            name='file_path2',
        ),
        migrations.AlterField(
            model_name='capdata',
            name='file_path',
            field=models.FileField(default='', upload_to='files'),
        ),
    ]
